name: Link Checker
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose 
            --method head 
            --max-concurrency 3 
            --accept 200,403,429 
            --user-agent "The-88x31-Project-Bot (https://auvreil.github.io/88x31/) (@kurvexa.proton.me)"
            "./buttons.json"
          fail: false 

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: "Links Checked | Report"
          content-filepath: ./lychee/out.md
          labels: report, automated
